[workspace]
members = [
    "tasks/e",
    "tasks/a",
    "tasks/i",
    "tasks/g",
    "tasks/m",
    "tasks/c",
  # "main",
  # DO not format this file.
  "algo_lib",
]

[profile.release]
debug = 1
